### ISSUE TITLE
KeyError without key in exception if country name not found

### ISSUE THREAD

**Issue by vgavro** [TuneLab/pycountry-convert#22]
Greetings! thanks for great work.
I see everywhere in your code this pattern:
```
if country_2_code not in COUNTRY_ALPHA2_TO_COUNTRY_NAME:
    raise KeyError
return COUNTRY_ALPHA2_TO_COUNTRY_NAME[country_2_code]
```
It's extremely *bad* pattern, as COUNTRY_ALPHA_2_TO_COUNTRY_NAME is dictionary anyway and will throw KeyError on this condition, but this KeyError will contain key string that was not found, and your exception doesn't contain it. It's very useful for debugging.
Consider this example:
```
In [5]: dct = {'x': 1, 'y': 2}

In [6]: if 'z' not in dct:
   ...:     raise KeyError
   ...: 
------------------------------------------------------------------------
KeyError                               Traceback (most recent call last)
<ipython-input-6-a1e0638bbdcf> in <module>()
      1 if 'z' not in dct:
----> 2     raise KeyError

KeyError: 

In [7]: dct['z']
------------------------------------------------------------------------
KeyError                               Traceback (most recent call last)
<ipython-input-7-eae397d049c2> in <module>()
----> 1 dct['z']

KeyError: 'z'
```

**Comment by ohadtune** [comment]
Thanks @vgavro  !! for the great comments.
Feel free to issue a PR with your suggestions.
Anyway we're planning on making some updates and improvements soon.

**Comment by jefftune** [comment]
@vgavro Will check this out today.

**Comment by jefftune** [comment]
@vgavro 
https://github.com/TuneLab/pycountry-convert/pull/29

**Comment by jefftune** [comment]
Resolved
