### ISSUE TITLE
Consider populate data for dictionaries also from pycountry?

### ISSUE THREAD

**Issue by vgavro** [TuneLab/pycountry-convert#23]
There is some country names, that are in pycountry, but not here.
I haven't found the code that generate this dictionaries. Maybe it would be better to also populate from pycountry (merge wikipedia and pycountry data)? (in my case there is 'PALESTINE, STATE OF' in pycountry, but not in your data https://www.iso.org/obp/ui/#iso:code:3166:PS). There are much country names that are not in pycountry, but in your library, but I think it would be nice to have one complete library, and if pycountry already have data from ISO, we can include it in dictionary generation. Would you commit the code generating dictionaries and i may add pull request with pycountry merge? What do you think about that? If you want to keep this library as helper for pycountry it's ok, but there is no need in much data here that are already in pycountry then? What do you think about that?

**Comment by vgavro** [comment]
I ended up with this, maybe it would be helpful for someone.
```
def create_country_name_to_alpha2():
    from pycountry import countries
    from pycountry_convert.country_name_to_country_alpha2 \
        import COUNTRY_NAME_TO_COUNTRY_ALPHA2

    rv = {k.upper(): v for k, v in COUNTRY_NAME_TO_COUNTRY_ALPHA2.items()}
    rv.update({
        'KOREA': 'KR',
        'PALESTINIAN TERRITORY': 'PS',
        'COTE D\'IVOIRE': 'CÔTE D\'IVOIRE',
    })
    for country in countries:
        for attr in ('name', 'common_name', 'official_name'):
            name = getattr(country, attr, None)
            if name:
                rv[name.upper()] = country.alpha_2
    return rv


COUNTRY_NAME_TO_ALPHA2 = create_country_name_to_alpha2()


def country_name_to_alpha2(name, raise_error=True):
    name = name.upper()
    try:
        return COUNTRY_NAME_TO_ALPHA2[name]
    except KeyError:
        if raise_error:
            raise
```

**Comment by davecremins** [comment]
I think merging the data available in `pycountry` would be beneficial to all users of this package 👍

**Comment by jefftune** [comment]
@davecremins @vgavro 
I will do so today

**Comment by jefftune** [comment]
@davecremins Doing so now

**Comment by jefftune** [comment]
@davecremins @vgavro
Modified, please review.
