### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by romanovskyj** [TuneLab/pycountry-convert#40]
Hi,

Could you please clarify if the library supports python2.7 version? From the badges, it looks like 2.7 is supported

![versions](https://img.shields.io/pypi/pyversions/pycountry-convert.svg?style=flat)

However, when I install the package for 2.7 version and try to import the function I get an error with `lru_cache` attribute:
```
AttributeError: 'module' object has no attribute 'lru_cache'
```

The reason that lru_cache is appeared starting at python 3.2

 So the question is: is 2.7 version still supported or not? Thank you!

**Comment by ToxicWar** [comment]
+1

**Comment by jefftune** [comment]
I will implement this

**Comment by jefftune** [comment]
To: @romanovskyj, @openp2pdesign, @ToxicWar 
Added support, waiting for review.

**Comment by hayorov** [comment]
It works! Thx

**Comment by zaquestion** [comment]
Thanks for confirming!
