### ISSUE TITLE
pycountry - consider adding "common_name" attribute

### ISSUE THREAD

**Issue by vgavro** [TuneLab/pycountry-convert#41]
There is "common_name" attribute (along with "official_name", which is parsed from pycountry already).
Right now there is only {'Bolivia', 'Moldova', 'Taiwan', 'Tanzania', 'Venezuela', 'Vietnam'}, which is contained in your wikipedia data already, but maybe it would be more clean to add this attribute from pycountry too (in case of future modifications).
Thanks for library!

**Comment by BlueT** [comment]
Important and a must-have.

**Comment by BlueT** [comment]
Not sure if I get you correctly, but I can see `common_name` in my python3 test.
![photo_2018-02-16_03-55-38](https://user-images.githubusercontent.com/51141/36278670-730b8bac-12cf-11e8-9bd5-9c2b651db26a.jpg)

**Comment by jefftune** [comment]
Thank you @vgavro Merged
