### ISSUE TITLE
country_name_to_alpha{2,3} optimization?

### ISSUE THREAD

**Issue by vgavro** [TuneLab/pycountry-convert#42]
Is there is a reason not to use lru_cache decorator on country_mappings.map_country_name_to_country_alpha{2,3}?
I believe this is an error, because this function executes every time for country_name_to_country_alpha{2,3} call.
Thanks for you work! (I'll create merge request for this and other my ticket in case you will want both tickets to be merged)

**Comment by jefftune** [comment]
Thank you @vgavro merged
